### ISSUE TITLE
Any documentation about how to use this library?

### ISSUE THREAD

**Issue by uriel-fanelli** [syncthing/protocol#11]
Hi

is there any documentation about how to use this library, **given the fact code is NOT documentation**?

thanks,

Uriel

**Comment by AudriusButkevicius** [comment]
Have you tried clicking on the godoc link on the front page?http://godoc.org/github.com/syncthing/protocol

**Comment by AudriusButkevicius** [comment]
This defines how the protocol works and what messages are doing what and exchanged when: https://github.com/syncthing/specs

Once you understand  the protcol spec, using the protocol package becomes self-explanatory.

**Comment by uriel-fanelli** [comment]
I think probably is very clear to you, because you wrote it... 

tanks in any case, 

Uriel

**Comment by AudriusButkevicius** [comment]
Just for the record, I haven't written anything, but I understood it by reading the spec and code when I needed something.
